# Generated by Django 3.2 on 2021-04-27 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gqm_api', '0004_metrics_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='metrics',
        ),
        migrations.DeleteModel(
            name='Metrics',
        ),
    ]
